from os import environ as env

PYTHON_CONSUMER_KEY = env.get("PYTHON_CONSUMER_KEY", None)
PYTHON_CONSUMER_SECRET = env.get("PYTHON_CONSUMER_SECRET", None)
PYTHON_ACCESS_TOKEN = env.get("PYTHON_ACCESS_TOKEN", None)
PYTHON_ACCESS_TOKEN_SECRET = env.get("PYTHON_ACCESS_TOKEN_SECRET", None)
